apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-code-app
      env: dev
  template:
    metadata:
      labels:
        app: qr-code-app
        env: dev
    spec:
      containers:
        - name: qr-code-app
          image: localhost/qr-code-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qr-code-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: qr-code-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080