apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-code-app
  template:
    metadata:
      labels:
        app: qr-code-app
    spec:
      containers:
        - name: qr-code-app
          image: localhost/qr-code-app:latest  # Updated to match Podman image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qr-code-app-service
spec:
  type: NodePort
  selector:
    app: qr-code-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080